### ISSUE TITLE
Xs can not get window screen on win11

### ISSUE THREAD

**Issue by longzhongba** [niart120/Project_Xs#3]
Hi bro, thank you for your job, it really helps me.
Recently I changed my pc to win11 system, Xs can run on win11,  but it can not get window screen on win11.

**Comment by niart120** [comment]
(using DeepL)
Thank you for reporting.

I'm aware that Project Xs does not support Windows 11, but I have no plans to do so.
Currently, I have released a more convenient tool than Project Xs, so please use that. (Apologies that the description is only in Japanese.)

Project eXcelSior : https://github.com/niart120/Project_eXcelSior/releases
Description (Japanese) : https://hackmd.io/@niart/SkCpMpk9n

(Original text)
報告してくださりありがとうございます.

Project XsがWindows11に対応していないのは把握していますが, 対応する予定はありません.
現在, Project Xsよりも利便性の高いツールを公開しているので, 基本的にはそちらを利用してください. (説明が日本語のものしかないのをお詫びします)

Project eXcelSior : https://github.com/niart120/Project_eXcelSior/releases
Description (日本語) : https://hackmd.io/@niart/SkCpMpk9n

**Comment by longzhongba** [comment]
邮件已收到

**Comment by longzhongba** [comment]
ty for the reply.
I'll try to use XsReader on win11
